using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;


[Serializable] public class TouchEvent : UnityEvent<Collider, bool> { }
public class OVRInputTest : MonoBehaviour
{
    [SerializeField] TMPro.TextMeshPro text;
    [SerializeField] OVRInput.Controller m_controller;
    OVRInputTest eventController;
    //public UnityEvent<GameObject> touchEvent = new UnityEvent<GameObject>();
    [SerializeField] private TouchEvent touchEvent = new TouchEvent();
    [SerializeField] private float wetherTriggerDown=0.5f;

    public KarutaSystem KarutaSystem;
    public GameSystem GameSystem;

    private OVRInput.Controller controller;
    private bool isTriggerDown = false;

    bool miss;
    float timer;

    public static OVRInputTest instanceOVRIn = null;
    public Collider hudaCollider=null;

    public bool GetIsTriggerDown()
    {
        return isTriggerDown;
    }
    void Start()
    {
        
        //controller = GetComponent<OVRControllerHelper>().m_controller;
    }

    void Update()
    {
        
            float value = OVRInput.Get(OVRInput.Axis1D.PrimaryIndexTrigger,m_controller);

            // ï¿½lï¿½ï¿½0ï¿½Å‚È‚ï¿½ï¿½ï¿½ÎAï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½ï¿½Triggerï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        
            if (value >= wetherTriggerDown)
            {
                isTriggerDown = true;
            
            }
            else
            {
                isTriggerDown = false;
            
            }
        
        
        if (miss == true)
        {
            timer += Time.deltaTime;
            if (timer >= 0.5)
            {
                miss = false;
            }
        }

    }




    /** ï¿½Ê‚ï¿½Collider(other)ï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Ôï¿½ï¿½s **/
   
    public void OnTriggerEnter(Collider other)
    {


        
        // ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½ï¿½Triggerï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Aï¿½ÎÛ‚ï¿½ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½gï¿½Å‚È‚ï¿½
        if (isTriggerDown==true && other.tag != "Player"&&miss==false)
        {
            if (text != null)
            {
                text.text = "tag:" + other.tag;
            }
            //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ç©ï¿½ï¿½ï¿½Å‘Å‚ï¿½ï¿½ï¿½ï¿½ï¿½Âiï¿½_ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½j

            if (other.gameObject.GetComponent<KarutaHuda>() == null)
            {
                return;
            }

            touchEvent.Invoke(other,true);
            //ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚Åï¿½ï¿½ï¿½ï¿½Å‘Å‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            // ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½Æ‚Â‚ï¿½ï¿½ñ‚¾ƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½transformï¿½ğ“¯Šï¿½

            
        }
    }
    public void Miss()
    {
        miss = true;
        timer = 0;
    }
   
    
        
    
}